import type { Area, DigestReport, LandParcel, MultifamilyAsset, Property } from "./types";

export const PROPERTIES: Property[] = [
  {
    id: "p-thicket",
    rank: 1,
    address: "403 Thicket Crest Road",
    city: "Seffner",
    state: "FL",
    zip: "33584",
    lat: 27.9984,
    lng: -82.2759,
    zillowUrl: "https://www.zillow.com/homes/403-Thicket-Crest-Road-Seffner-FL-33584_rb/",
    thesis: "full-rehab",
    description:
      "Investor / full rehab opportunity. Vacant for 5 years — needs roof, drywall, HVAC, plumbing, kitchen, bathrooms, flooring, and landscaping. Basis is the story: buy at a discount, recap after a gut, then rent or refinance.",
    beds: 3,
    baths: 2,
    sqft: 1480,
    yearBuilt: 2004,
    ask: 199400,
    offer: 193894,
    rent: 2247,
    taxMonthly: 344,
    hoaMonthly: 71,
    insuranceMonthly: 76,
    mortgageMonthly: 645,
    cashFlow: 1756,
    vacancyNote: "Vacant 5 years",
    tags: ["Full rehab", "Seffner", "Low HOA"],
    areaSlug: "seffner",
  },
  {
    id: "p-hammocks",
    rank: 2,
    address: "1715 Hammocks Avenue #1715",
    city: "Lutz",
    state: "FL",
    zip: "33549",
    lat: 28.1512,
    lng: -82.4614,
    zillowUrl: "https://www.zillow.com/homes/1715-Hammocks-Avenue-Lutz-FL-33549_rb/",
    thesis: "turnkey",
    description:
      "Move-in ready 3-bedroom, 2-bath. Spacious primary suite with two walk-in closets and an en-suite with tub and shower. Scenic setting — rent-ready with limited capex.",
    beds: 3,
    baths: 2,
    sqft: 1620,
    yearBuilt: 2006,
    ask: 235000,
    offer: 230870,
    rent: 2066,
    taxMonthly: 102,
    hoaMonthly: 375,
    insuranceMonthly: 90,
    mortgageMonthly: 768,
    cashFlow: 1499,
    tags: ["Turnkey", "Lutz", "Condo/TH"],
    areaSlug: "lutz",
  },
  {
    id: "p-ashburn",
    rank: 3,
    address: "4617 Ashburn Square Drive",
    city: "Tampa",
    state: "FL",
    zip: "33610",
    lat: 27.9951,
    lng: -82.3794,
    zillowUrl: "https://www.zillow.com/homes/4617-Ashburn-Square-Drive-Tampa-FL-33610_rb/",
    thesis: "cashflow",
    description:
      "2010 corner townhome in Ashburn Square. Stylish, in the heart of Tampa Bay, with a workable HOA and in-place rent that still covers the High ROI screen.",
    beds: 3,
    baths: 2.5,
    sqft: 1588,
    yearBuilt: 2010,
    ask: 249900,
    offer: 245100,
    rent: 2064,
    taxMonthly: 321,
    hoaMonthly: 247,
    insuranceMonthly: 96,
    mortgageMonthly: 815,
    cashFlow: 1400,
    tags: ["Townhome", "Tampa 33610", "2010+"],
    areaSlug: "east-tampa",
  },
  {
    id: "p-blackwater",
    rank: 4,
    address: "1033 Blackwater Drive",
    city: "Wesley Chapel",
    state: "FL",
    zip: "33543",
    lat: 28.2106,
    lng: -82.3278,
    zillowUrl: "https://www.zillow.com/homes/1033-Blackwater-Drive-Wesley-Chapel-FL-33543_rb/",
    thesis: "turnkey",
    description:
      "Immaculately maintained corner unit in gated Tullamore. 3 bed / 2.5 bath, 1,832 sqft — Wiregrass-adjacent demand and a tenant pool that pays for schools and gates.",
    beds: 3,
    baths: 2.5,
    sqft: 1832,
    yearBuilt: 2014,
    ask: 250000,
    offer: 246450,
    rent: 2097,
    taxMonthly: 281,
    hoaMonthly: 335,
    insuranceMonthly: 96,
    mortgageMonthly: 820,
    cashFlow: 1385,
    tags: ["Tullamore", "Gated", "Wesley Chapel"],
    areaSlug: "wesley-chapel",
  },
  {
    id: "p-gossamer",
    rank: 5,
    address: "31150 Gossamer Way",
    city: "Zephyrhills",
    state: "FL",
    zip: "33543",
    lat: 28.2311,
    lng: -82.2734,
    zillowUrl: "https://www.zillow.com/homes/31150-Gossamer-Way-Zephyrhills-FL-33543_rb/",
    thesis: "cashflow",
    description:
      "3 / 2.5, 1,559 sqft townhome in Meadow Pointe. Virtually staged. Community amenities and I-75 access keep this liquid for both tenants and a 5-year exit.",
    beds: 3,
    baths: 2.5,
    sqft: 1559,
    yearBuilt: 2005,
    ask: 235000,
    offer: 229600,
    rent: 2062,
    taxMonthly: 511,
    hoaMonthly: 266,
    insuranceMonthly: 90,
    mortgageMonthly: 764,
    cashFlow: 1195,
    tags: ["Meadow Pointe", "Zephyrhills"],
    areaSlug: "zephyrhills",
  },
  {
    id: "p-winding",
    rank: 6,
    address: "4535 Winding River Way",
    city: "Land O Lakes",
    state: "FL",
    zip: "34639",
    lat: 28.2189,
    lng: -82.4572,
    zillowUrl: "https://www.zillow.com/homes/4535-Winding-River-Way-Land-O-Lakes-FL-34639_rb/",
    thesis: "turnkey",
    description:
      "Price reduced for a quick sale. Immaculate, low-maintenance townhome with a redesigned kitchen. Land O Lakes / Lutz / Wesley Chapel triangle.",
    beds: 3,
    baths: 2.5,
    sqft: 1520,
    yearBuilt: 2008,
    ask: 250000,
    offer: 247300,
    rent: 1836,
    taxMonthly: 317,
    hoaMonthly: 240,
    insuranceMonthly: 96,
    mortgageMonthly: 823,
    cashFlow: 1183,
    tags: ["Price cut", "Land O Lakes"],
    areaSlug: "land-o-lakes",
  },
  {
    id: "p-goodwick",
    rank: 7,
    address: "30148 Goodwick Way",
    city: "Zephyrhills",
    state: "FL",
    zip: "33543",
    lat: 28.2264,
    lng: -82.2811,
    zillowUrl: "https://www.zillow.com/homes/30148-Goodwick-Way-Zephyrhills-FL-33543_rb/",
    thesis: "cashflow",
    description:
      "Coming soon. Two-story Mediterranean townhome in gated Tullamore — 3 / 2.5 and a 1-car garage. Affordable Wesley Chapel living on the Zephyrhills side of the gate.",
    beds: 3,
    baths: 2.5,
    sqft: 1680,
    yearBuilt: 2013,
    ask: 230000,
    offer: 226400,
    rent: 1995,
    taxMonthly: 400,
    hoaMonthly: 335,
    insuranceMonthly: 88,
    mortgageMonthly: 753,
    cashFlow: 1172,
    tags: ["Coming soon", "Tullamore"],
    areaSlug: "wesley-chapel",
  },
  {
    id: "p-rollingbrook",
    rank: 8,
    address: "16342 Rollingbrook Drive",
    city: "Odessa",
    state: "FL",
    zip: "33556",
    lat: 28.1867,
    lng: -82.5914,
    zillowUrl: "https://www.zillow.com/homes/16342-Rollingbrook-Drive-Odessa-FL-33556_rb/",
    thesis: "cashflow",
    description:
      "3 / 2.5 two-story in gated Swan View. New carpet, open kitchen, screened patio facing conservation. Super-low HOA for Odessa.",
    beds: 3,
    baths: 2.5,
    sqft: 1610,
    yearBuilt: 2007,
    ask: 235000,
    offer: 230870,
    rent: 1797,
    taxMonthly: 323,
    hoaMonthly: 232,
    insuranceMonthly: 90,
    mortgageMonthly: 768,
    cashFlow: 1152,
    tags: ["Odessa", "Conservation", "Gated"],
    areaSlug: "odessa",
  },
  {
    id: "p-daliha",
    rank: 9,
    address: "37557 Daliha Terrace",
    city: "Zephyrhills",
    state: "FL",
    zip: "33542",
    lat: 28.2378,
    lng: -82.1812,
    zillowUrl: "https://www.zillow.com/homes/37557-Daliha-Terrace-Zephyrhills-FL-33542_rb/",
    thesis: "value-add",
    description:
      "2009 two-story townhome. Wood cabinetry, stainless, breakfast bar opening to the living space. Lowest basis on this week's list — cash flow holds even with a modest rent.",
    beds: 3,
    baths: 2.5,
    sqft: 1540,
    yearBuilt: 2009,
    ask: 182000,
    offer: 175822,
    rent: 1813,
    taxMonthly: 314,
    hoaMonthly: 285,
    insuranceMonthly: 70,
    mortgageMonthly: 585,
    cashFlow: 1144,
    tags: ["Lowest basis", "Zephyrhills"],
    areaSlug: "zephyrhills",
  },
  {
    id: "p-garden-wall",
    rank: 10,
    address: "36427 Garden Wall Way",
    city: "Zephyrhills",
    state: "FL",
    zip: "33541",
    lat: 28.2441,
    lng: -82.2108,
    zillowUrl: "https://www.zillow.com/homes/36427-Garden-Wall-Way-Zephyrhills-FL-33541_rb/",
    thesis: "turnkey",
    description:
      "No carpet. $5,000 closing-cost assistance. Move-in ready 3 / 2.5, 1,600+ sqft. Taxes are the drag — underwrite the millage before you stretch the offer.",
    beds: 3,
    baths: 2.5,
    sqft: 1620,
    yearBuilt: 2011,
    ask: 245000,
    offer: 242200,
    rent: 1893,
    taxMonthly: 541,
    hoaMonthly: 275,
    insuranceMonthly: 94,
    mortgageMonthly: 806,
    cashFlow: 983,
    tags: ["Closing credit", "High tax"],
    areaSlug: "zephyrhills",
  },
];

export const AREAS: Area[] = [
  {
    slug: "wesley-chapel",
    name: "Wesley Chapel",
    county: "Pasco",
    zips: ["33543", "33544", "33545"],
    lat: 28.2397,
    lng: -82.3279,
    investorScore: 86,
    medianAsk: 242000,
    medianRent: 2040,
    medianCf: 1280,
    yoyPrice: 4.8,
    yoyRent: 3.1,
    vacancy: 4.2,
    jobGrowth: 3.4,
    population: 72800,
    medianHhIncome: 92400,
    floodRisk: "moderate",
    schoolScore: 8,
    walkScore: 38,
    commuteMin: 28,
    thesis:
      "Best renter demand in the MSA for gated 3/2.5 townhomes. Wiregrass, I-75, and medical employment keep absorption tight. HOA and insurance are the two numbers that kill an otherwise clean deal.",
    risks: ["HOA rental caps in Tullamore / Meadow Pointe", "Insurance re-quotes", "New BTR supply along SR-56"],
    catalysts: ["I-75 / SR-56 jobs", "Wiregrass schools", "In-migration from Tampa proper"],
  },
  {
    slug: "zephyrhills",
    name: "Zephyrhills",
    county: "Pasco",
    zips: ["33541", "33542", "33543"],
    lat: 28.2336,
    lng: -82.1812,
    investorScore: 81,
    medianAsk: 228000,
    medianRent: 1920,
    medianCf: 1120,
    yoyPrice: 5.6,
    yoyRent: 3.8,
    vacancy: 5.1,
    jobGrowth: 2.2,
    population: 19800,
    medianHhIncome: 58400,
    floodRisk: "moderate",
    schoolScore: 6,
    walkScore: 32,
    commuteMin: 34,
    thesis:
      "Lowest basis on the High ROI list. Cash flow is real if you underwrite taxes — millage here is the swing factor versus Wesley Chapel. Best for value-add and first-time investors.",
    risks: ["Higher millage / tax drag", "Tenant quality variance", "Flood pockets east of US-301"],
    catalysts: ["Overflow from Wesley Chapel pricing", "US-301 retail", "Sub-$200k inventory"],
  },
  {
    slug: "lutz",
    name: "Lutz",
    county: "Hillsborough / Pasco",
    zips: ["33548", "33549", "33558"],
    lat: 28.1511,
    lng: -82.4615,
    investorScore: 79,
    medianAsk: 238000,
    medianRent: 2010,
    medianCf: 1320,
    yoyPrice: 3.9,
    yoyRent: 2.6,
    vacancy: 3.8,
    jobGrowth: 2.1,
    population: 23600,
    medianHhIncome: 88600,
    floodRisk: "low",
    schoolScore: 8,
    walkScore: 28,
    commuteMin: 26,
    thesis:
      "Turnkey townhome / villa product with strong owner-occupant exit. HOAs run high; you buy the schools and the commute, not the millage.",
    risks: ["HOA $300–400 is common", "Limited distressed inventory", "Condo questionnaire delays"],
    catalysts: ["Northdale / Lutz Lake Fern demand", "A-rated pockets", "Low flood relative to coastal Hillsborough"],
  },
  {
    slug: "east-tampa",
    name: "East Tampa / 33610",
    county: "Hillsborough",
    zips: ["33610", "33619"],
    lat: 27.995,
    lng: -82.379,
    investorScore: 74,
    medianAsk: 249000,
    medianRent: 2050,
    medianCf: 1380,
    yoyPrice: 6.2,
    yoyRent: 4.1,
    vacancy: 6.4,
    jobGrowth: 2.8,
    population: 41200,
    medianHhIncome: 51200,
    floodRisk: "moderate",
    schoolScore: 4,
    walkScore: 46,
    commuteMin: 18,
    thesis:
      "In-city basis with actual renters. 2010+ townhomes (Ashburn Square class) clear the High ROI screen if you stay out of flood and crime micro-pockets. Better cash-on-cash than Wesley Chapel once HOA is honest.",
    risks: ["Crime micro-pockets", "Flood / drainage", "School scores limit owner-occupant exit"],
    catalysts: ["Port / warehouse jobs", "I-4 / I-75 junction", "City infill rents"],
  },
  {
    slug: "seffner",
    name: "Seffner",
    county: "Hillsborough",
    zips: ["33584"],
    lat: 27.998,
    lng: -82.276,
    investorScore: 77,
    medianAsk: 215000,
    medianRent: 1980,
    medianCf: 1480,
    yoyPrice: 5.1,
    yoyRent: 3.4,
    vacancy: 5.8,
    jobGrowth: 1.9,
    population: 16800,
    medianHhIncome: 62800,
    floodRisk: "low",
    schoolScore: 5,
    walkScore: 24,
    commuteMin: 22,
    thesis:
      "Full-rehab hunting ground. Low HOA SFR product still exists under $200k. Vacant houses like Thicket Crest are the highest-CF names on the digest when you can stomach the capex.",
    risks: ["Capex overruns on 5-year vacancies", "Appraisal gaps on gut rehabs", "Shallower tenant pool than Wesley Chapel"],
    catalysts: ["I-4 corridor", "Sub-$200k SFR", "Low HOA vs. gated Pasco"],
  },
  {
    slug: "land-o-lakes",
    name: "Land O Lakes",
    county: "Pasco",
    zips: ["34638", "34639"],
    lat: 28.219,
    lng: -82.457,
    investorScore: 76,
    medianAsk: 248000,
    medianRent: 1880,
    medianCf: 1160,
    yoyPrice: 4.2,
    yoyRent: 2.4,
    vacancy: 4.0,
    jobGrowth: 2.7,
    population: 35900,
    medianHhIncome: 97800,
    floodRisk: "moderate",
    schoolScore: 8,
    walkScore: 22,
    commuteMin: 32,
    thesis:
      "Owner-occupant gravity. Rents lag asking prices, so cash flow is thinner than Zephyrhills. Buy on price cuts (Winding River) or skip.",
    risks: ["Rent lag vs. price", "HOA + CDD stacking in some communities", "Lakes / flood panels"],
    catalysts: ["A-rated schools", "Suncoast Pkwy", "Household income"],
  },
  {
    slug: "odessa",
    name: "Odessa",
    county: "Hillsborough / Pasco",
    zips: ["33556"],
    lat: 28.187,
    lng: -82.591,
    investorScore: 72,
    medianAsk: 239000,
    medianRent: 1820,
    medianCf: 1140,
    yoyPrice: 3.6,
    yoyRent: 2.1,
    vacancy: 3.5,
    jobGrowth: 1.8,
    population: 7600,
    medianHhIncome: 112400,
    floodRisk: "low",
    schoolScore: 8,
    walkScore: 18,
    commuteMin: 30,
    thesis:
      "Conservation townhomes with a high-income renter. Low HOA is the edge. Liquidity is thinner — underwrite a longer days-on-market on exit.",
    risks: ["Thin rental comps", "HOA rental approval", "Longer DOM"],
    catalysts: ["High HHI", "Conservation premium", "Veterans Expwy access"],
  },
];

export const LAND: LandParcel[] = [
  {
    id: "l-us301",
    address: "Vacant — US-301 & Chancey Road",
    city: "Zephyrhills",
    zip: "33541",
    lat: 28.251,
    lng: -82.198,
    acres: 4.6,
    zoning: "RM-16 / PD eligible",
    floodZone: "X (0.2% annual)",
    utilities: ["Water at curb", "Sewer 420 ft", "Power"],
    asking: 795000,
    pricePerAcre: 172826,
    buildableSf: 130244,
    maxUnits: 36,
    investorScore: 84,
    thesis:
      "Garden multifamily pad on the cheap side of Wesley Chapel demand. Sewer extension is the go/no-go. If concurrency clears, 36 doors at $145k/door basis is an IC-level deal.",
    comps: [
      { address: "Fort King Rd vacant, Zephyrhills", acres: 3.1, price: 620000, closed: "Mar 2026" },
      { address: "Eiland Blvd pad, Zephyrhills", acres: 5.2, price: 980000, closed: "Nov 2025" },
    ],
    scenarios: [
      { name: "Hold 24 mo", units: 0, cost: 92000, exitValue: 870000, profit: 75000, roi: 9.4 },
      { name: "Townhome pad (18)", units: 18, cost: 3120000, exitValue: 5220000, profit: 1305000, roi: 33.1 },
      { name: "Garden MF (36)", units: 36, cost: 5480000, exitValue: 7560000, profit: 1285000, roi: 20.5 },
    ],
    areaSlug: "zephyrhills",
  },
  {
    id: "l-sr54",
    address: "Vacant — SR-54 west of Curley",
    city: "Wesley Chapel",
    zip: "33543",
    lat: 28.218,
    lng: -82.294,
    acres: 1.15,
    zoning: "C-1 / mixed-use overlay",
    floodZone: "X",
    utilities: ["Water", "Sewer", "Power", "Fiber"],
    asking: 649000,
    pricePerAcre: 564348,
    buildableSf: 32500,
    maxUnits: 12,
    investorScore: 71,
    thesis:
      "Infill mixed-use. Basis is retail-land pricing; residential only works as stacked flats or a medical-office conversion. Pass as pure multifamily unless the seller splits.",
    comps: [
      { address: "SR-54 outparcel, Wesley Chapel", acres: 0.9, price: 720000, closed: "Jan 2026" },
    ],
    scenarios: [
      { name: "Hold / land bank", units: 0, cost: 48000, exitValue: 710000, profit: 61000, roi: 8.7 },
      { name: "12-unit stacked flats", units: 12, cost: 2480000, exitValue: 3120000, profit: 0, roi: 0.1 },
      { name: "Medical office 8k sf", units: 0, cost: 1680000, exitValue: 2420000, profit: 91000, roi: 3.9 },
    ],
    areaSlug: "wesley-chapel",
  },
  {
    id: "l-mlk",
    address: "Vacant — E Martin Luther King Jr Blvd",
    city: "Tampa",
    zip: "33610",
    lat: 27.981,
    lng: -82.391,
    acres: 0.42,
    zoning: "RM-24",
    floodZone: "AE (panel 12057C)",
    utilities: ["Water", "Sewer", "Power"],
    asking: 189000,
    pricePerAcre: 450000,
    buildableSf: 9800,
    maxUnits: 8,
    investorScore: 78,
    thesis:
      "Small infill multifamily. Flood AE means elevated first floor and a real insurance line. 6–8 small units still beats buying a $250k townhome on a per-door basis.",
    comps: [
      { address: "40th St vacant, Tampa", acres: 0.31, price: 155000, closed: "Feb 2026" },
    ],
    scenarios: [
      { name: "Hold", units: 0, cost: 14000, exitValue: 210000, profit: 21000, roi: 10.1 },
      { name: "6-plex (elevated)", units: 6, cost: 980000, exitValue: 1380000, profit: 211000, roi: 18.0 },
      { name: "8 micro-units", units: 8, cost: 1180000, exitValue: 1640000, profit: 271000, roi: 19.8 },
    ],
    areaSlug: "east-tampa",
  },
];

export const MULTIFAMILY: MultifamilyAsset[] = [
  {
    id: "mf-meadow",
    name: "Meadow Glen Apartments",
    address: "28410 State Road 54",
    city: "Wesley Chapel",
    zip: "33543",
    lat: 28.216,
    lng: -82.341,
    yearBuilt: 1998,
    units: 48,
    occupancy: 94,
    asking: 6_850_000,
    offer: 6_520_000,
    gpr: 921600,
    egi: 866304,
    expenses: 355184,
    noi: 511120,
    capRate: 7.84,
    grm: 7.07,
    pricePerUnit: 135833,
    debtYield: 12.05,
    unitMix: [
      { type: "1 bed / 1 bath", count: 16, rent: 1350 },
      { type: "2 bed / 1 bath", count: 24, rent: 1625 },
      { type: "3 bed / 2 bath", count: 8, rent: 1895 },
    ],
    investorScore: 88,
    thesis:
      "Value-add garden product inside the Wesley Chapel renter shed. In-place rents trail market by ~$140/door. Insurance and 1990s systems are the questions to ask; the cap is honest at this basis.",
    risks: ["Florida insurance", "Deferred roof / HVAC", "New Class A down SR-54"],
    areaSlug: "wesley-chapel",
  },
  {
    id: "mf-301",
    name: "301 Flats",
    address: "37820 5th Avenue",
    city: "Zephyrhills",
    zip: "33542",
    lat: 28.233,
    lng: -82.181,
    yearBuilt: 1986,
    units: 16,
    occupancy: 91,
    asking: 1_895_000,
    offer: 1_760_000,
    gpr: 249600,
    egi: 229632,
    expenses: 98600,
    noi: 131032,
    capRate: 7.45,
    grm: 7.05,
    pricePerUnit: 110000,
    debtYield: 11.46,
    unitMix: [
      { type: "1 bed / 1 bath", count: 8, rent: 1150 },
      { type: "2 bed / 1 bath", count: 8, rent: 1450 },
    ],
    investorScore: 82,
    thesis:
      "True small-balance multifamily. Sub-$120k/door in a cash-flow zip. Needs a rent roll audit and a plumbing camera. Perfect add-on for an investor already buying Zephyrhills townhomes.",
    risks: ["Age of plumbing", "Owner-finance rumors vs. actual debt", "Crime at the node"],
    areaSlug: "zephyrhills",
  },
  {
    id: "mf-ybor-edge",
    name: "10th Ave Walk-Ups",
    address: "5108 E 10th Avenue",
    city: "Tampa",
    zip: "33619",
    lat: 27.965,
    lng: -82.401,
    yearBuilt: 1972,
    units: 8,
    occupancy: 88,
    asking: 1_125_000,
    offer: 1_040_000,
    gpr: 153600,
    egi: 135168,
    expenses: 62200,
    noi: 72968,
    capRate: 7.02,
    grm: 6.77,
    pricePerUnit: 130000,
    debtYield: 10.79,
    unitMix: [{ type: "2 bed / 1 bath", count: 8, rent: 1600 }],
    investorScore: 69,
    thesis:
      "East Tampa walk-up. Basis works; operations are the product. Pass if you are not set up for self-manage or a local 8–20 unit operator. Flood and insurance quotes before LOI.",
    risks: ["Flood AE adjacent", "Self-manage requirement", "Capex on 1972 electric"],
    areaSlug: "east-tampa",
  },
];

export const DIGEST: DigestReport = {
  id: "digest-2026-08-21",
  title: "Sam's High ROI Picks",
  date: "Friday, August 21, 2026",
  source: "REIP · High ROI digest",
  intro:
    "Top 10 Greater Tampa deals ranked by cash flow. Mortgage estimated at 7% fixed, 30-year, 50% down. All figures are estimates.",
  deals: PROPERTIES,
};

export function propertyById(id: string) {
  return PROPERTIES.find((p) => p.id === id);
}

export function areaBySlug(slug: string) {
  return AREAS.find((a) => a.slug === slug);
}

export function landById(id: string) {
  return LAND.find((l) => l.id === id);
}

export function mfById(id: string) {
  return MULTIFAMILY.find((m) => m.id === id);
}

export const KPIS = {
  dealsScreened: 142,
  digestCount: PROPERTIES.length,
  avgCashFlow: Math.round(PROPERTIES.reduce((s, p) => s + p.cashFlow, 0) / PROPERTIES.length),
  avgOffer: Math.round(PROPERTIES.reduce((s, p) => s + p.offer, 0) / PROPERTIES.length),
  markets: AREAS.length,
};
