export const LOAN_OFFICER = {
  name: "Arki Koul",
  title: "Mortgage Loan Originator",
  nmls: "2030350",
  phone: "813-712-9591",
  phoneHref: "tel:+18137129591",
  email: "Arki@shopwisemortgage.com",
  emailHref: "mailto:Arki@shopwisemortgage.com",
  company: "Shopwise Mortgage",
  companyNmls: "2412164",
  website: "https://www.shopwisemortgage.com",
  websiteLabel: "www.shopwisemortgage.com",
  licensedIn: "FL, GA, TX",
  addressLines: ["3250 West Big Beaver Road", "Suite 229", "Troy, MI 48084"],
  photoSrc: "/arki-koul-card.png",
} as const;
